name: Readme
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/readme@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Deepak5310
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
